version: "3.8"

services:
  flask-app:
    image: flask-car-scraper  # Use the local image
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - flask_scraper:/app  # Use named volume for persistence
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    working_dir: /app
    command: gunicorn -w 4 -b 0.0.0.0:5000 app:app

volumes:
  flask_scraper:
    external: true
